# Generated by Django 4.1.3 on 2022-11-09 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_studio", "0002_alter_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movie_studio.genre"),
        ),
        migrations.AddField(
            model_name="movie",
            name="staff",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.ManyToManyField(related_name="staff", to="movie_studio.role"),
        ),
    ]
